#CONTAINS DATA STRUCTURE DEFINITIONS

from dataclasses import dataclass  #python decorator -- automatically creates a class for holding data
from typing import Optional #optional tells we may keep field value none (empty)

@dataclass
class Session:  #session: one participants complete journey through the app
    """Represents one participant's complete app session"""
    session_id: str
    participant_id: str
    start_time: int
    status: str
    end_time: Optional[int] = None       #optional cause may not be required everytime for every user
    device_model: Optional[str] = None
    android_version: Optional[str] = None
    screen_width: Optional[int] = None
    screen_height: Optional[int] = None
    age_range: Optional[str] = None
    gender: Optional[str] = None
    consent_time: Optional[int] = None

    def to_dict(self):
        """Converts Session to dictionary for database storage"""
        return {
            'session_id': self.session_id,
            'participant_id': self.participant_id,
            'start_time': self.start_time,
            'end_time': self.end_time,
            'status': self.status,
            'device_model': self.device_model,
            'android_version': self.android_version,
            'screen_width': self.screen_width,
            'screen_height': self.screen_height,
            'age_range': self.age_range,
            'gender': self.gender,
            'consent_time': self.consent_time
        }

@dataclass
class KeystrokeEvent:
    """Represents a single keystroke with all timing and touch data"""
    session_id: str  #to be made by Person A at consent screen
    task_type: str
    key_id: str
    key_char: str
    press_time_ms: int
    release_time_ms: int
    hold_duration_ms: int
    inter_key_interval_ms: Optional[int]
    flight_time_ms: Optional[int]
    touch_x: float
    touch_y: float
    key_center_x: float
    key_center_y: float
    pressure: Optional[float] = None
    touch_size: Optional[float] = None #stressed --> press harder --> larger touch area
    is_backspace: bool = False
    is_error: bool = False
    position_in_sentence: int = 0 #position in fixed sentences defined in constants.py
    event_id: Optional[int] = None #not needed for  now

    def to_dict(self):
        """Convert KeystrokeEvent to dictionary for database storage"""
        return {
            'event_id': self.event_id,
            'session_id': self.session_id,
            'task_type': self.task_type,
            'key_id': self.key_id,
            'key_char': self.key_char,
            'press_time_ms': self.press_time_ms,
            'release_time_ms': self.release_time_ms,
            'hold_duration_ms': self.hold_duration_ms,
            'inter_key_interval_ms': self.inter_key_interval_ms,
            'flight_time_ms': self.flight_time_ms,
            'touch_x': self.touch_x,
            'touch_y': self.touch_y,
            'key_center_x': self.key_center_x,
            'key_center_y': self.key_center_y,
            'pressure': self.pressure,
            'touch_size': self.touch_size,
            'is_backspace': self.is_backspace,
            'is_error': self.is_error,
            'position_in_sentence': self.position_in_sentence
        }

@dataclass
class EmotionLabel:
    """Represents the emoji and typed sentence after each task: not for typing itself, but result summary after typing"""
    session_id: str
    task_type: str
    selected_emoji: str
    typed_sentence: str
    expected_sentence: str
    is_exact_match: bool
    typing_duration_ms: int
    total_keystrokes: int
    backspace_count: int
    label_id: Optional[int] = None
    submission_time: Optional[int] = None #when the user submitted a specific task, that time

    def to_dict(self):
        """Convert EmotionLabel to dictionary for database storage"""
        return {
            'label_id': self.label_id,
            'session_id': self.session_id,
            'task_type': self.task_type,
            'selected_emoji': self.selected_emoji,
            'typed_sentence': self.typed_sentence,
            'expected_sentence': self.expected_sentence,
            'is_exact_match': self.is_exact_match,
            'typing_duration_ms': self.typing_duration_ms,
            'total_keystrokes': self.total_keystrokes,
            'backspace_count': self.backspace_count,
            'submission_time': self.submission_time
        }

@dataclass
class GameResult:
    """Represents the outcome of one game/task"""
    session_id: str
    task_type: str
    final_score: int
    outcome: str #no actual pass/fail criteria --- so no real outcome
    start_time: int
    end_time: int
    duration_ms: int
    attempts: int = 1 #most probably won't be needed, 
    result_id: Optional[int] = None #autogenerated by database

    def to_dict(self):
        """Convert GameResult to dictionary for database storage"""
        return {
            'result_id': self.result_id,
            'session_id': self.session_id,
            'task_type': self.task_type,
            'final_score': self.final_score,
            'outcome': self.outcome,
            'start_time': self.start_time,
            'end_time': self.end_time,
            'duration_ms': self.duration_ms,
            'attempts': self.attempts
        }